[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Omer Katz <omer.drow@gmail.com>"]
description = ""
name = "jumpstarter"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.7.0"
transitions = { git = "git@github.com:pytransitions/transitions.git", branch = "master", extras = ['diagrams']}
# transitions = { version = "^0.8.7", extras = ['diagrams'] }
transitions-anyio = "^0.2.0"
wrapt = "^1.12.1"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^20.8b1"
isort = "^5.7.0"
mock = { version = "^4.0.3", python = "< 3.8" }
pytest = "^6.0"
pytest-cov = "^2.11.1"
pytest-github-actions-annotate-failures = "^0.1.1"
pytest-monkeytype = "^1.1.0"
pytest-randomly = "^3.4"
pytest-subtests = "^0.3"
pytest-xdist = "^2.2.0"
pyupgrade = "^2.7.4"
sphinx-celery = "^2.0.0"
toml-sort = "^0.18.0"
trio = "^0.17"

[tool.poetry.extras]
diagrams = ["transitions"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    'ignore:A private pytest class or function was used.:pytest.PytestDeprecationWarning'
]
